### ISSUE TITLE
ZeroDivisonError: division by zero

### ISSUE THREAD

**Issue by YoonsungNam** [dcslab-snu/iso-sched#38]
아래와 같이 FG의 MetricDiff를 계산할 때, 종종 ZeroDivisonError가 발생함.
아마도 bench_launcher에서 값이 제대로 안넘어 오는 것 같음

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "controller.py", line 224, in run
    self._isolate_workloads()
  File "controller.py", line 154, in _isolate_workloads
    group.choose_next_isolator()
  File "/home/dcslab/ysnam/projects/iso-sched/isolating_controller/isolation/policies/greedy_diff_with_violation_policy.py", line 47, in choose_next_isolator
    if super().choose_next_isolator():
  File "/home/dcslab/ysnam/projects/iso-sched/isolating_controller/isolation/policies/greedy_diff_policy.py", line 25, in choose_next_isolator
    resource: ResourceType = self.contentious_resource()
  File "/home/dcslab/ysnam/projects/iso-sched/isolating_controller/isolation/policies/base_policy.py", line 54, in contentious_resource
    metric_diff: MetricDiff = self._fg_wl.calc_metric_diff()
  File "/home/dcslab/ysnam/projects/iso-sched/isolating_controller/workload.py", line 126, in calc_metric_diff
    return MetricDiff(curr_metric, solorun_data)
  File "/home/dcslab/ysnam/projects/iso-sched/isolating_controller/metric_container/basic_metric.py", line 125, in __init__
    self._l3_hit_ratio = curr.l3hit_ratio - prev.l3hit_ratio
  **File "/home/dcslab/ysnam/projects/iso-sched/isolating_controller/metric_container/basic_metric.py", line 103, in l3hit_ratio
    return 1 - self._l3miss / self._l2miss
ZeroDivisionError: division by zero**

**Comment by YoonsungNam** [comment]
위의 에러를 재현하려면, canneal과 SP를 수행 후, canneal이 끝나면서 해당 에러메시지가 뜬다.

**Comment by isac322** [comment]
63c665d 에서 해결
